### ISSUE TITLE
Track speed

### ISSUE THREAD

**Issue by KwatMDPhD** [KwatMDPhD/Kwat.jl#17]
ef09dbf8b29c2450da50da3e7e7dd42b13b6b319

![Screen Shot 2021-10-14 at 11 46 24](https://user-images.githubusercontent.com/7741548/137369879-39967fb1-54d0-4fd4-9841-0601aa1f9c5a.png)
![Screen Shot 2021-10-14 at 11 46 43](https://user-images.githubusercontent.com/7741548/137369892-72da7f86-97c1-4a6c-a644-4910df8d738c.png)
![Screen Shot 2021-10-14 at 11 47 10](https://user-images.githubusercontent.com/7741548/137369903-35835626-07d5-46cf-8b17-c6cb1dd7ab4d.png)
![Screen Shot 2021-10-14 at 11 47 32](https://user-images.githubusercontent.com/7741548/137369910-20b26d5c-6cfb-4925-985d-63a616ab2898.png)
![Screen Shot 2021-10-14 at 11 47 51](https://user-images.githubusercontent.com/7741548/137369917-b74dfdc0-cf08-431e-bd60-4d570f719803.png)
![Screen Shot 2021-10-14 at 11 48 10](https://user-images.githubusercontent.com/7741548/137369920-9e9dcedb-d815-452b-963c-ffbb112e534a.png)

**Comment by KwatME** [comment]
ce1677f343b3a2837a42e00384fd89d0d8b7ec19
![Screen Shot 2021-10-14 at 11 52 03](https://user-images.githubusercontent.com/7741548/137370392-4b2d6cdf-9462-4c81-a14f-6a87fcb60d0a.png)
![Screen Shot 2021-10-14 at 11 52 08](https://user-images.githubusercontent.com/7741548/137370381-7329fd83-81d1-4590-ad06-efc03c1b97d6.png)
![Screen Shot 2021-10-14 at 11 52 12](https://user-images.githubusercontent.com/7741548/137370384-e737a52e-b842-42fd-8465-8dbe69db9e3b.png)
![Screen Shot 2021-10-14 at 11 52 16](https://user-images.githubusercontent.com/7741548/137370387-62df13e9-d7a9-4ec4-a931-479b8d7a2ef5.png)
![Screen Shot 2021-10-14 at 11 52 20](https://user-images.githubusercontent.com/7741548/137370390-84b24332-e296-4cc2-b184-b11fb0abd919.png)
![Screen Shot 2021-10-14 at 11 52 25](https://user-images.githubusercontent.com/7741548/137370391-60ccb81e-61ca-4750-a3e3-1fd5379a377b.png)
![Screen Shot 2021-10-14 at 11 52 29](https://user-images.githubusercontent.com/7741548/137370393-f546f780-f97b-45ce-814d-1f3c5b779b26.png)
9
